### ISSUE TITLE
ImportError for vim_bridge

### ISSUE THREAD

**Issue by urschrei** [nvie/vim-pyunit#20]
I'm getting an ImportError every time I open a .py file:

```
Error detected while processing /Users/sth/.vim/ftplugin/python_pyunit.vim:
line  485:
Traceback (most recent call last):
    File "<string>", line 4, in <module>
ImportError: No module named vim_bridge
```

This despite the fact that I have vim-bridge (0.5) installed, and can import and print its `__dict__` from a script. All vim-pyunit's own unit tests pass, and I can run nose using F8/Shift F8. Any idea where the error's coming from?

Running Python 2.7 on OS X

**Comment by nvie** [comment]
Could it be that your Vim is compiled with a hard-coded path to a different version of Python or that you've installed vim_bridge in a Python virtual env that Vim does not run Python from?

**Comment by urschrei** [comment]
Hmm. It's definitely not a virtualenv issue, and I'm just using the standard latest MacVim binary. Is there any way I can figure out if it's calling a different Python binary than `/usr/bin/env Python` is?

## 

steph

**Comment by urschrei** [comment]
It _was_ the MacVim default, which is linked against an earlier Python. Building it myself fixed it. Thanks for pointing me in the right direction.

**Comment by nvie** [comment]
No problemo, have fun.
