### ISSUE TITLE
Failing to find the root dir of my project

### ISSUE THREAD

**Issue by holandes22** [nvie/vim-pyunit#22]
Hi,

I have a root hierarchy like this:

project
&nbsp;&nbsp;&nbsp;&nbsp;\- setup.py
&nbsp;&nbsp;&nbsp;&nbsp;+project
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+foo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-bar.py
&nbsp;&nbsp;&nbsp;&nbsp;+tests
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+foo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-test_bar.py

The tests folder follows the same hierarchy as the source folder.
And my settings in vimrc are as follows:
let g:ProjRootIndicators = [".git", "setup.py"]
let g:PyUnitTestsStructure = "nose"
let g:PyUnitTestsRoot = "tests"

When I try to run the tests, it doesn't find the test file and it actually tries to create one with the path
project/foo/tests/foo/test_bar.py
which does not exists. It should be tests/foo/test_bar.py, starting at the root project root.

I tried also setting PyUnitSourceRoot = "project", but same results. I'm not sure if this would work either as the name of the project changes (I tend not to use 'src' as a folder name to store the source code but the same name as project/repo)

Any ideas what am I doing wrong?

**Comment by holandes22** [comment]
Ok, got it running. My bad, I failed to understand that I should open vim from the project root and then open the file. 
Is there a way to avoid this? meaning, find the the project path disregarding my current position?

**Comment by nvie** [comment]
I agree this plugin isn't quite trivial. There are too many test frameworks / directory layouts that are in use out there.

I'm thinking of rewriting this plugin from scratch once in a way that is agnostic about what command to run and from where. The trick is, though, that pressing `<F9>` from the source file should be able to find the accompanying test file, and there simply isn't always a single, unambiguous counterpart file.

If you have any suggestions for simplifying this plugin, they are very welcome.
