### ISSUE TITLE
Not ignoring codes in `g:flake8_ignore`?

### ISSUE THREAD

**Issue by dpo** [nvie/vim-pyunit#23]
- Vim 7.3 in OSX 10.8.2 compiled with home-made homebrew formula by pulling directly from Google's hg repository.
- Python 2.7.3 compiled as Framework using standard homebrew formula.
- `flake8` installed using `pip install flake8`
- `vim-flake8` plugin installed with Pathogen.

In `~/.vimrc`:

```
let g:flake8_ignore="E225"
```

Expected result: no more pesky messages about E225 (missing whitespace around operator).

Actual result: E225 isn't ignored at all...

**Comment by nvie** [comment]
Thanks, this has been bugging the plugin for some time, I finally took the time to actually solve it.

**Comment by nvie** [comment]
Btw: it's solved in the nvie/vim-flake8 project, not in this repo.

**Comment by dpo** [comment]
Thanks much! Not sure how my issue ended up in this repo. Must be my error...
